name: Android CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  debug-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Decode and save google-services.json
      if: ${{ env.GOOGLE_SERVICES_JSON_BASE64 != '' }}
      env:
        GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
      run: |
        echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
        echo "google-services.json has been created successfully"

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew assembleDebug

    - name: Generate coverage report
      run: ./gradlew jacocoTestReport

    - name: Add coverage to PR
      id: jacoco
      uses: takumi-saito/jacoco-report@v1.5
      with:
        paths: ${{ github.workspace }}/app/build/reports/jacocoTestReport/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        debug-mode: true
